### ISSUE TITLE
TypeError: The key argument of `Registry.get` must be a str, got <class 'type'>

### ISSUE THREAD

**Issue by PanXiongAdam** [wusize/F-LMM#16]
Hello, we train the model, but have this issue:

Traceback (most recent call last):
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/xtuner/tools/train.py", line 360, in <module>
    main()
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/xtuner/tools/train.py", line 356, in main
    runner.train()
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/runner/_flexible_runner.py", line 1182, in train
    self.strategy.prepare(
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/_strategy/deepspeed.py", line 381, in prepare
    model = self.build_model(model)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/_strategy/base.py", line 306, in build_model
    model = MODELS.build(model)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/ssd_raid5/LISA/F-LMM/flmm/models/frozen_deepseek_vl.py", line 91, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/ssd_raid5/LISA/F-LMM/flmm/models/frozen_deepseek_vl.py", line 36, in __init__
    self.mask_head = BUILDER.build(mask_head)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mnt/ssd_raid5/LISA/F-LMM/flmm/models/mask_head/mask_decoder.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmseg/models/backbones/unet.py", line 387, in __init__
    BasicConvBlock(
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmseg/models/backbones/unet.py", line 64, in __init__
    ConvModule(
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 148, in __init__
    self.norm_name, norm = build_norm_layer(
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmcv/cnn/bricks/norm.py", line 105, in build_norm_layer
    norm_layer = registry.get(layer_type)
  File "/mnt/ssd_raid5/LISA/anaconda3/envs/flmm/lib/python3.8/site-packages/mmengine/registry/registry.py", line 441, in get
    raise TypeError(
TypeError: The key argument of `Registry.get` must be a str, got <class 'type'>

please can you tell me how to solve it? thank you

**Comment by cryingdxy** [comment]
Could you please tell me the solution? I met the same question as you

**Comment by panxiong1994** [comment]
@cryingdxy It's been too long—I've already forgotten the exact modification method. My MMCV version is 2.0.1, so it might be a version-related issue.

**Comment by cryingdxy** [comment]
@PanXiongAdam Thanks a lot! By the way, could you please tell me the version of torch and transformers, I met some new problems.

**Comment by panxiong1994** [comment]
@cryingdxy Sorry, I made a typo in the version numbers.
The correct versions are:
mmcv==2.1.0 or 2.0.1 (most likely 2.1.0)
mmseg==1.2.2
transformer==4.39.1
torch==2.0.1 or 2.1.0 (most likely 2.0.1—you can try it out).

**Comment by cryingdxy** [comment]
Thansks！By the way, what is the version of Python?



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 20, 2025 21:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wusize/F-LMM] TypeError: The key argument of `Registry.get` mustbe a str, got <class 'type'&gt; (Issue #16)


panxiong1994 left a comment (wusize/F-LMM#16)
 
@cryingdxy Sorry, I made a typo in the version numbers.
 The correct versions are:
 mmcv==2.1.0 or 2.0.1 (most likely 2.1.0)
 mmseg==1.2.2
 transformer==4.39.1
 torch==2.0.1 or 2.1.0 (most likely 2.0.1—you can try it out).

**Comment by panxiong1994** [comment]
> Thansks！By the way, what is the version of Python?
> […](#)

python==3.8.20

**Comment by cryingdxy** [comment]
Ok. What's the version of cuda?



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 20, 2025 21:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wusize/F-LMM] TypeError: The key argument of `Registry.get` mustbe a str, got <class 'type'&gt; (Issue #16)


panxiong1994 left a comment (wusize/F-LMM#16)
  
Thansks！By the way, what is the version of Python?
 …
  
python==3.8.20
